apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-81ac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-81ac
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-81ac
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-81ac
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-81ac
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tiwv-tenant/rhtap-demo-app/hacbs-test-project-81ac@sha256:27381ce061c45f712f2fb304dd508b1a7394d3cb4aa39f00a08bbcb939878b1d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
