apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-81ac
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tiwv-tenant/rhtap-demo-app/hacbs-test-project-81ac@sha256:c33bd6f906eb08d94496616db6e1f4b9046bbf16743f39ede28b5f3995a33e79
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
